---
meta:
  bosh:
    target: (( merge ))
    username: (( merge ))
    password: (( merge ))
  aws:
    access_key_id: (( merge ))
    secret_access_key: (( merge ))
    region_name: us-east-1
    bosh_init:
      bucket: (( merge ))
  docker:
    email: (( merge ))
    username: (( merge ))
    password: (( merge ))

jobs:
- name: job-build-bosh-init-cli
  public: true
  serial: true
  plan:
  - aggregate:
    - get: bosh-init
      resource: git-bosh-init
  - task: bosh-init-cli-build
    config:
      platform: linux
      image: docker:///concourse/static-golang
      inputs:
        - name: bosh-init
          path: gopath/src/github.com/cloudfoundry/bosh-init
      run:
        path: gopath/src/github.com/cloudfoundry/bosh-init/bin/build
  - put: s3-bosh-init
    params:
      from: bosh-init-cli-build/gopath/src/github.com/cloudfoundry/bosh-init/out/bosh-init

- name: job-repackage-bosh-init-aws
  public: true
  serial: true
  plan:
  - aggregate:
    - get: s3-bosh-init
      passed: [job-build-bosh-init-cli]
    - get: cpi
      resource: git-bosh-init-aws-cpi
  - task: prepare-aws-docker-image
    config:
      platform: linux
      image: docker:///concourse/static-golang
      inputs:
        - name: s3-bosh-init
        - name: cpi
      run:
        path: cp
        args: ["s3-bosh-init/bosh-init", "cpi/"]
  - put: bosh-init-aws-docker-image
    params:
      build: prepare-aws-docker-image/cpi

- name: job-repackage-bosh-init-openstack
  public: true
  serial: true
  plan:
  - aggregate:
    - get: s3-bosh-init
      passed: [job-build-bosh-init-cli]
    - get: cpi
      resource: git-bosh-init-openstack-cpi
  - task: prepare-openstack-docker-image
    config:
      platform: linux
      image: docker:///concourse/static-golang
      inputs:
        - name: s3-bosh-init
        - name: cpi
      run:
        path: cp
        args: ["s3-bosh-init/bosh-init", "cpi/"]
  - put: bosh-init-openstack-docker-image
    params:
      build: prepare-openstack-docker-image/cpi

resources:
- name: git-bosh-init
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-init.git
    branch: master
- name: s3-bosh-init
  type: s3
  source:
    access_key_id: (( meta.aws.access_key_id ))
    secret_access_key: (( meta.aws.secret_access_key ))
    region_name: (( meta.aws.region_name ))
    bucket:  (( meta.aws.bosh_init.bucket ))
    private: false

- name: git-bosh-init-aws-cpi
  type: git
  source:
    uri: https://gist.github.com/db1126b8456bcaa854f3.git

- name: git-bosh-init-openstack-cpi
  type: git
  source:
    uri: https://gist.github.com/db1126b8456bcaa854f3.git

- name: bosh-init-aws-docker-image
  type: docker-image
  source:
    email: (( meta.docker.email ))
    username: (( meta.docker.username ))
    password: (( meta.docker.password ))
    repository: (( meta.docker.username "/bosh-init-aws" ))

- name: bosh-init-openstack-docker-image
  type: docker-image
  source:
    email: (( meta.docker.email ))
    username: (( meta.docker.username ))
    password: (( meta.docker.password ))
    repository: (( meta.docker.username "/bosh-init-openstack" ))
