---
jobs:
- name: job-build-bosh-init-cli
  public: true
  serial: true
  plan:
  - aggregate:
    - get: bosh-init
      resource: git-bosh-init
    - get: tutorial
      resource: git-tutorial
  - task: bosh-init-cli-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: concourse/static-golang}
      inputs:
        - name: bosh-init
          path: gopath/src/github.com/cloudfoundry/bosh-init
        - name: tutorial
      run:
        path: tutorial/60_multi_jobs_bosh_micro_build/task-bosh-init-cli-build.sh
      outputs:
        - name: build
  - task: ls
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu, tag: "14.04"}
      inputs:
        - name: build
          path: gopath/src/github.com/cloudfoundry/bosh-init
      run:
        path: ls
        args: ["-opR", "gopath/src/github.com/cloudfoundry/bosh-init/out"]

resources:
- name: git-bosh-init
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-init.git
    branch: master

- name: git-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git
    branch: update-for-2.2.1
