---
jobs:
- name: job-deploy
  public: true
  serial: true
  plan:
  - aggregate:
    - get: resource-bosh-stemcell
    - get: resource-bosh-release-redis
    - get: redis-release
      resource: resource-redis-release-templates
      params:
        submodules: none
    - get: stub
      resource: resource-deployment-manifest-stub

  - task: spiff-merge
    config:
      platform: linux
      image: {{docker-hub-image-47-tasks-uri}}
      inputs:
      - name: stub
      - name: redis-release
      run:
        path: spiff-merge-and-save
        args:
          - stub/manifest.yml
          - redis-release/templates/deployment.yml
          - redis-release/templates/jobs.yml
          - redis-release/templates/infrastructure-warden.yml
          - stub/stub.yml

  - task: git-add
    config:
      platform: linux
      image: {{docker-hub-image-47-tasks-uri}}
      inputs:
      - name: spiff-merge
      run:
        path: git-add-all
        args: [spiff-merge/stub]

  - put: resource-deployment-manifest-stub
    params:
      repository: git-add/spiff-merge/stub

resources:
- name: resource-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: {{bosh-stemcell-name}}

- name: resource-bosh-release-redis
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/redis-boshrelease

- name: resource-redis-release-templates
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/redis-boshrelease.git

- name: resource-deployment-manifest-stub
  type: git
  source:
    uri: git@gist.github.com:/395869dfd717644becf1.git
    branch: master
    private_key: {{github-private-key}}
