---
jobs:
- name: job-hello-world
  public: true
  serial: true
  plan:
  - task: hello-world
    config:
      platform: linux
      image: docker:///busybox
      run:
        path: echo
        args: [hello world]
