---
meta:
  docker:
    email: (( merge ))
    username: (( merge ))
    password: (( merge ))

jobs:
- name: job-publish
  public: true
  serial: true
  plan:
  - get: resource-tutorial
  - put: resource-41-docker-image
    params:
      build: resource-tutorial/41_dummy_resource_docker_image/docker

resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/drnic/concourse-tutorial.git

- name: resource-41-docker-image
  type: docker-image
  source:
    email: (( meta.docker.email ))
    username: (( meta.docker.username ))
    password: (( meta.docker.password ))
    repository: (( meta.docker.username "/resource-41-docker-image" ))
