jobs:
- name: job-github-release
  public: true
  serial: true
  plan:
  - get: github-release-spiff
  - task: ls
    config:
      platform: linux
      image: docker:///ubuntu#14.04
      inputs:
      - name: github-release-spiff
      run:
        path: ls
        args: ["-opR", "."]
resources:
- name: github-release-spiff
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: spiff
