jobs:
- name: job-cf-cli-release
  public: true
  serial: true
  plan:
  - get: cloudfoundry-cli-release
  - task: ls
    config:
      platform: linux
      image: docker:///ubuntu#14.04
      inputs:
      - name: cloudfoundry-cli-release
      run:
        path: ls
        args: ["-opR", "."]
resources:
- name: cloudfoundry-cli-release
  type: github-release
  source:
    user: cloudfoundry
    repository: cli
